#!/usr/bin/env bash
#
# h0neybadg3r b00str4pp3r
#
# Homepage: https://j3rm.io
#
# b00strap that shit, son!
#
#	$ curl https://j3rm.io/bootstrap | bash
#	 or
#	$ wget -qO- https://j3rm.io/bootstrap | bash
#
# Install ZSH
sudo apt install -y zsh && \
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" && \

# Install dotfiles
# git clone https://github.com/jermdw/dotfiles.git


